# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fit_linear_model_rcpp <- function(X, Y) {
    .Call(`_BIOSTAT625_HW3_fit_linear_model_rcpp`, X, Y)
}

calculate_r_squared <- function(Y, fitted) {
    .Call(`_BIOSTAT625_HW3_calculate_r_squared`, Y, fitted)
}

